BEGIN;
-- binary_copy should copy data binary from country;
-- ./spec/binary_copy_spec.rb:8;
CREATE EXTENSION os_name;
CREATE TABLE before (a os_name);
INSERT INTO before VALUES ('android'), ('ios'), ('windows'), ('ios'), ('unknown');
CREATE TABLE after (a os_name);
COPY before TO '/tmp/tst' WITH (FORMAT binary);
COPY after FROM '/tmp/tst' WITH (FORMAT binary);
SELECT * FROM after;
ROLLBACK;
